[package]
name = "const_fn_trait_ref_impls_feature_gate_brök"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
